name: cargaapp_mobile
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  animate_do: ^3.0.2
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  file_picker: ^5.3.0
  #  firebase_core: ^2.10.0
  #  firebase_messaging: ^14.4.1
  flutter:
    sdk: flutter
  flutter_credit_card: ^4.0.1
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.4
  font_awesome_flutter: ^10.4.0
  iconsax: ^0.0.8
  loading_indicator: ^3.1.0
  lottie: ^2.6.0
  provider: ^6.0.5
  smooth_page_indicator: ^1.0.1
  supabase_flutter: ^1.10.21
  url_launcher: ^6.1.11
  very_good_analysis: ^4.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/lottie/
